
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhljuacyrxxodlriqkgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVobGp1YWN5cnh4b2Rscmlxa2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDcwMzMsImV4cCI6MjA2MDMyMzAzM30.ceQEgnX0ObFj4UYa5XRq0Bai64i2FbXMu-EwVvo24us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
